### ISSUE TITLE
Create general rule: If a class has a name and text, they must be 1:1

### ISSUE THREAD

**Issue by ASL-rmarshall** [cdisc-org/ddf-core-poc#104]
Create rule defined for #98

**Comment by ASL-rmarshall** [comment]
Rule was deleted as superfluous in DDF Phase 4. Saving a copy of the draft definition:
```yaml
Authorities:
  - Organization: 'CDISC'
    Standards:
      - Name: USDM
        References:
          - Citations:
              - Cited Guidance: 'USDM'
                Document: 'USDM v2.6'
            Origin: USDM Conformance Rules
            Rule Identifier:
              Id: 'DDF99991'
              Version: '1'
            Validator Rule Message: 'If a class has a name and a text, then for the
              instances of that class within a StudyDesign, the name and the
              text must be one to one.'
            Version: '1.0'
        Version: '3.0'
Check:
  all:
    - name: 'name'
      operator: non_empty
    - name: 'text'
      operator: non_empty
    - name: 'name'
      operator: is_not_unique_relationship
      value: 'text'
Core:
  Id: ''
  Status: Draft
  Version: '1'
Description: If a class/entity has a name and a text, the name and text must be one to one.
Executability: Fully Executable
Outcome:
  Message: There is more than one class/entity text for a name, or more than one
    name for a text for a class/entity.
  Output Variables:
    - parent_entity
    - parent_id
    - parent_rel
    - id
    - name
    - text
Rule Type: Record Data
Scope:
  Entities:
    Include:
      - ALL

Sensitivity: Record
```
