### ISSUE TITLE
Create rule DDF00021: A relationship cannot exist between an instance of a class and itself

### ISSUE THREAD

**Issue by ASL-rmarshall** [cdisc-org/ddf-core-poc#116]
Create single-target relationship rule defined for #115

**Comment by ASL-rmarshall** [comment]
Split into two separate rules, which both need to be review:
- DDF00021: check that the `id` value is not the same as `previousId`, `nextId` and `defaultConditionId` (when specified).
- DDF00022: check that the `id` value is not the same as an value in `childrenIds` (when specified).

**Comment by ASL-rmarshall** [comment]
@gerrycampion

For DDF00021, is it OK for there to be "Absent-Variable Skips" for this type of rule (when the dataset does not contain any of the variables)? I tried combining "equal_to" with "exists" but it didn't make any difference.

For DDF00022, the rule editor is reporting a schema violation for the "Multiple_Values" dataset (because it contains the underscore). I included the underscore deliberately so that it was more obvious that this is not actually a dataset representing a class.  Should the schema be updated to allow the underscore or would it be better to rename the sheet, do you think?

**Comment by gerrycampion** [comment]
@ASL-rmarshall 
21 - "Absent Variable Skips" are perfectly normal positive results if they are expected.
22 - Whatever you think is a better representation. I have no reservations about updating the schema if we like it that way better.

**Comment by DianeWold** [comment]
I ran the positive test data successfully, but when I tried to run the negative test data, I got a message that the data was "not implemented."

**Comment by DianeWold** [comment]
Although the negative test data for DDF00021 ran during Thursday's meeting, and the results showed the rule fired 11 times, the number expected, When I tried to run the test again, I got the "not implemented" error, then on another attempt, "NetworkError when attempting to fetch resource".
I'm going to assume that the test data, which ran successfully for three of us on different occassions, is okay, and that the other errors are fluke.  Under this assumption, I am moving this issue to "Done"

**Comment by ASL-rmarshall** [comment]
This rule to only report where `rel_type = "definition"`. Associated test data have been updated and unit tests have been rerun successfully.

**Comment by ASL-rmarshall** [comment]
Saving POC rule definition before overwriting for DDF4:
```yaml
Authorities:
  - Organization: 'CDISC'
    Standards:
      - Name: USDM
        References:
          - Citations:
              - Cited Guidance: 'USDM'
                Document: "USDM v2.6"
            Origin: USDM Conformance Rules
            Rule Identifier:
              Id: 'DDF00021'
              Version: '1'
            Validator Rule Message: 'The relationship links an entity instance to itself,
              which is invalid'
            Version: '1.0'
        Version: '3.0'
Check:
  all:
    - name: rel_type
      operator: equal_to
      value: 'reference'
    - name: parent_id
      operator: equal_to
      value: id
Core:
  Id: CORE-000414
  Status: Draft
  Version: '1'
Description: "A relationship cannot link an instance of a class to itself. If
  specified, any value of previousId, nextId, defaultConditionId, or any
  childrenIds must not be the same as the value of id."
Executability: Fully Executable
Outcome:
  Message: "The relationship links an entity instance to itself (previousId,
    nextId, defaultConditionId, or any childrenIds is the same as id), which is
    invalid"
  Output Variables:
    - parent_entity
    - parent_id
    - parent_rel
    - id
Rule Type: Record Data
Scope:
  Entities:
    Include:
      - All
Sensitivity: Record
```
