### ISSUE TITLE
Create r:ule: StudyEpoch ordered (StudyDesign components)

### ISSUE THREAD

**Issue by ASL-rmarshall** [cdisc-org/ddf-core-poc#117]
Create StudyDesign components for #

**Comment by ASL-rmarshall** [comment]
Saving a copy of the POC rule definition before overwriting for DDF 4:
```yaml
Authorities:
  - Organization: 'CDISC'
    Standards:
      - Name: USDM
        References:
          - Citations:
              - Cited Guidance: 'USDM'
                Document: 'USDM v2.6'
              - Cited Guidance: 'SDTMIG'
                Document: 'SDTMIG v3.4'
                Section: '7.2.1'
            Origin: USDM Conformance Rules
            Release Notes: ''
            Rule Identifier:
              Id: 'DDF00024'
              Version: '1'
            Validator Rule Message: ''
            Version: '1.0'
        Version: '3.0'
Check:
  all:
    #- name: nextId
    #  operator: empty
    #- name: nextId
    #  operator: is_unique_set
    #  value: parent_id
    - name: $study_design_ids
      operator: shares_exactly_one_element_with
      value: $study_design_ids_with_epoch
    #- name: nextId
    #  operator: empty
    #    - not:
    #        name: $study_design_ids
    #        operator: shares_exactly_one_element_with
    #        value: parent_id
Core:
  Status: Draft
  Version: '1'
Description: 'The StudyEpochs of a StudyDesign are ordered correctly according
  to the specifed nextId and previousId values.'
Executability: Fully Executable
Operations:
  - domain: STUDYDESIGN
    id: $study_design_ids
    name: id
    operator: distinct
  - domain: STUDYEPOCH
    id: $study_design_ids_with_epoch
    name: parent_id
    operator: distinct
Outcome:
  Message: 'The StudyEpochs of a StudyDesign are not ordered correctly according
    to the specifed nextId and previousId values: both nextId and previousId are
    missing, the id value specified for nextId or previousId is not one of the
    epoch ids for the StudyDesign, or the same id value has been used more than
    once as nextId or previousId within the StudyDesign.'
  Output Variables:
    - $study_design_ids
    - $study_design_ids_with_epoch
Rule Type: Variable Metadata Check
Scope:
  Entities:
    Include:
      - StudyEpoch
Sensitivity: Dataset
```
