### ISSUE TITLE
Create rule DDF00026: The ids of the StudyProtocolDocumentVersions associated with a StudyProtocolDocument are all distinct.

### ISSUE THREAD

**Issue by ASL-rmarshall** [cdisc-org/ddf-core-poc#120]
Create rule defined for #113

**Comment by ASL-rmarshall** [comment]
Changed DDF99986 to DDF00026. Modified the description and output message to refer to "id values" instead of "ids" to make it clear that it's only the value of the `id` attribute that are being checked.

Ready for review.

**Comment by ASL-rmarshall** [comment]
Note that the imported dataset is named "STUDYPROTOCOLDOCUMENTVERSIO" (without an "N" at the end).  I have raised issue #126 about this.

**Comment by DianeWold** [comment]
The rule seems okay, but test data seems to be missing.

**Comment by DianeWold** [comment]
I'm getting the message "unit-test-coreid-DDF00025-negative Not implemented" in a box with the title "File Upload" I have to leave now, but perhaps we can sort this out Thursday morning.
![image](https://github.com/cdisc-org/ddf-core-poc/assets/149505078/0ead5ccd-9d9f-4f62-a3f0-85a7a3bbe5b8)

**Comment by DianeWold** [comment]
Matt helped me synch the test data, which I think will resolve my issues.
I ran the test data for DDF00026 and got the expected results.

**Comment by ASL-rmarshall** [comment]
Rule deleted in DDF Phase 4. Saving a copy of the definition:
```yaml
Authorities:
  - Organization: 'CDISC'
    Standards:
      - Name: USDM
        References:
          - Citations:
              - Cited Guidance: 'USDM 2.6'
                Document: 'USDM v2.6'
            Origin: USDM Conformance Rules
            Rule Identifier:
              Id: 'DDF00026'
              Version: '1'
            Validator Rule Message: 'No two versions of a study protocol document have the same id.'
            Version: '1.0'
        Version: '3.0'
Check:
  all:
    - name: id
      operator: is_not_unique_set
      value:
        - parent_id
Core:
  Id: CORE-000418
  Status: Draft
  Version: '1'
Description: 'The StudyProtocolVersions associated with a StudyProtocolDocument
  must all have different id values'
Executability: Fully Executable
Outcome:
  Message: 'The id values of the StudyProtocolVersions associated with a
    StudyProtocolDocument include duplicates.'
  Output Variables:
    - parent_entity
    - parent_id
    - id
    - protocolVersion
    - protocolStatus.decode
Rule Type: Record Data
Scope:
  Entities:
    Include:
      - StudyProtocolDocumentVersion
Sensitivity: Record

```
