### ISSUE TITLE
Create rule DDF00025: If a Timing is of type "Fixed reference" then window, windowLower, and windowUpper are all null.

### ISSUE THREAD

**Issue by ASL-rmarshall** [cdisc-org/ddf-core-poc#121]
Create rule defined for #118

**Comment by ASL-rmarshall** [comment]
Changed DDF99987 to DDF00025. The rule reports an error if any of `window`, `windowLower` or `windowUpper` is non-empty and either `type.code` is "C201558" or `type.decode` is "Fixed Reference" (ignoring text case).  This is ready for review.

**Comment by DianeWold** [comment]
Negative test data returned 3 errors, as expected. Positive data returned no errors.

**Comment by ASL-rmarshall** [comment]
Saving a copy of the POC rule definition before overwriting for DDF 4:
``` yaml
Authorities:
  - Organization: 'CDISC'
    Standards:
      - Name: USDM
        References:
          - Citations:
              - Cited Guidance: 'USDM 2.6'
                Document: 'USDM v2.6'
            Origin: USDM Conformance Rules
            Rule Identifier:
              Id: 'DDF00025'
              Version: '1'
            Version: '1.0'
        Version: '3.0'
Check:
  all:
    - any:
        - name: window
          operator: non_empty
        - name: windowLower
          operator: non_empty
        - name: windowUpper
          operator: non_empty
    - any:
        - name: type.code
          operator: equal_to
          value: C201358
        - name: type.decode
          operator: equal_to_case_insensitive
          value: Fixed Reference
Core:
  Id: CORE-000417
  Status: Draft
  Version: '1'
Description: 'An anchor cannot have a window. If a Timing is of type "fixed
  reference" then window, windowLower and windowUpper are all null'
Executability: Fully Executable
Outcome:
  Message: 'A Timing of type "fixed reference" has one or more attributes of a
    window, which is not allowed.'
  Output Variables:
    - parent_entity
    - parent_id
    - parent_rel
    - id
    - type.code
    - type.decode
    - window
    - windowLower
    - windowUpper
Rule Type: Record Data
Scope:
  Entities:
    Include:
      - Timing
Sensitivity: Record
```
