### ISSUE TITLE
Create rule DDF00041: Each primary objective must contain at least one primary endpoint, and each primary endpoint must be contained by a primary objective.

### ISSUE THREAD

**Issue by ASL-rmarshall** [cdisc-org/ddf-core-poc#125]
Create rule defined for #112

**Comment by ASL-rmarshall** [comment]
This is not blocked - should be able to use the same logic as for DDF00034 (see #146)

**Comment by ASL-rmarshall** [comment]
The implementation of this rule relies on the fact that "level" is only reference to `Code` from `Objective`.  We can therefore create a `distinct` list of all `code`s and `decode`s by `parent_id`.  When this is joined to `Endpoint` (by `parent_id`) it is only the `Objective.level` codes and decodes that will be linked.

**Comment by ASL-rmarshall** [comment]
@BSnoeijerCD @DianeWold This is now ready for review. The negative and positive test data is similar - it shows 8 endpoints for 3 objectives (two primary and one secondary). In the negative test data, the level is swapped for the 2nd and 3rd objectives.  Only 6 negative results are expected (for each of the endpoints in the 2nd and 3rd objectives), but 7 are reported due to the Scope issue (the rule runs against the `Code` dataset too and an invalid negative is reported.

**Comment by DianeWold** [comment]
Ran the negative test data, which returned 7 errors:
- Rows 3-5 primary endpoints for a secondary objective
- Rows 6-8 secondary endpoints for a primary objective
- one error from trying to run the rule on the Code dataset.
Ran the positive test data, which returned two positives.  Don't quite understand why 2 instead of 1.

**Comment by ASL-rmarshall** [comment]
@DianeWold There are 2 positives for the same reason that there is one (negative) error for the `Code` - it is the `Scope` issue.  Although, the `Scope` indicates the rule should only be run for the `Endpoint` dataset, it is being run for both the `Endpoint` and `Code` datasets.
- For the negative test data, an issue is being reported for the `Code` dataset because the rule only reports the primary objective without any primary endpoints (it can't report primary endpoints in a non-primary objective because the `Code` dataset doesn't contain the `level.code` and `level.decode` columns that are needed to identify primary endpoints).
- For the positive test data, no issue is reported for the `Code` dataset because all the objectives that have `level = "Primary Objective"` also have at primary endpoints (and, again, the rule can't report primary endpoints in a non-primary objective because the `Code` dataset doesn't contain the `level.code` and `level.decode` columns that are needed to identify primary endpoints).

**Comment by DianeWold** [comment]
My brain gets tangled trying to understand this, but I believe that the test data ran successfully.

**Comment by BSnoeijerCD** [comment]
@ASL-rmarshall : this one needs to be reconsidered since it does not check the direct relationship between the objective and the corresponding endpoint. It only checks that if a primary exists in one it also exists in the other class.

**Comment by ASL-rmarshall** [comment]
Saving a copy of the POC rule specification before overwriting for DDF4:
```yaml
Authorities:
  - Organization: 'CDISC'
    Standards:
      - Name: USDM
        References:
          - Citations:
              - Cited Guidance: 'USDM 2.6'
                Document: 'USDM v2.6'
            Origin: USDM Conformance Rules
            Rule Identifier:
              Id: 'DDF00041'
              Version: '1'
            Validator Rule Message: ''
            Version: '1.0'
        Version: '3.0'
Check:
  any:
    - all:
        - any:
            - name: $obj_level_code
              operator: contains_case_insensitive
              value: 'C85826'
            - name: $obj_level_decode
              operator: contains_case_insensitive
              value: 'Trial Primary Objective'
        - name: $ep_level_codes
          operator: does_not_contain_case_insensitive
          value: 'C94496'
        - name: $ep_level_decodes
          operator: does_not_contain_case_insensitive
          value: 'Primary Endpoint'
    - all:
        - name: $obj_level_code
          operator: does_not_contain_case_insensitive
          value: 'C85826'
        - name: $obj_level_decode
          operator: does_not_contain_case_insensitive
          value: 'Trial Primary Objective'
        - any:
            - name: level.code
              operator: equal_to_case_insensitive
              value: 'C94496'
            - name: level.decode
              operator: equal_to_case_insensitive
              value: 'Primary Endpoint'
Core:
  Id: CORE-000450
  Status: Draft
  Version: '1'
Description: 'Each primary objective must contain at least one primary endpoint,
  and each primary endpoint must be contained by a primary objective.'
Executability: Fully Executable
Operations:
  - domain: ENDPOINT
    group:
      - parent_id
    id: $ep_level_codes
    name: level.code
    operator: distinct
  - domain: ENDPOINT
    group:
      - parent_id
    id: $ep_level_decodes
    name: level.decode
    operator: distinct
  - domain: CODE
    group:
      - parent_id
    id: $obj_level_code
    name: code
    operator: distinct
  - domain: CODE
    group:
      - parent_id
    id: $obj_level_decode
    name: decode
    operator: distinct
Outcome:
  Message: 'There are no primary endpoints for a primary objective, or a primary
    endpoint is not contained by a primary objective.'
  Output Variables:
    - parent_entity
    - parent_id
    - $obj_level_code
    - $obj_level_decode
    - id
    - level.code
    - level.decode
Rule Type: Record Data
Scope:
  Entities:
    Include:
      - Endpoint
Sensitivity: Record
```
