### ISSUE TITLE
Create rule DDF00029: For classes with next and previous relationships, the next and previous relationships must establish an ordered list of instances of the class (valid Encounter id values for nextId and previousId).

### ISSUE THREAD

**Issue by ASL-rmarshall** [cdisc-org/ddf-core-poc#134]
Create rule to check for valid `nextId` and `previousId` values for Encounter as defined for #89

**Comment by ASL-rmarshall** [comment]
@DianeWold And another one. This is checking the valid `id` values are used in `nextId` and `previousId` in the `Encounter` class.

**Comment by DianeWold** [comment]
Ran negative test data, and rules engine found the 4 errors:
Row 1: previousID is not an encounter in this study design (not in the data)
Row 4: nextID is an encounter in the wrong study design.
Row 6: previousID is an encounter in the wrong study design.
Row 7: nextID is not an encounter in this study design (not in data)
Positive data ran as expected.

**Comment by ASL-rmarshall** [comment]
This rule has been updated to only report where `rel_type = "definition"`. Associated test data have been updated and unit tests have been rerun successfully.

**Comment by ASL-rmarshall** [comment]
Saving a copy of the POC rule definition before overwriting for DDF 4:
```yaml
Authorities:
  - Organization: 'CDISC'
    Standards:
      - Name: USDM
        References:
          - Citations:
              - Cited Guidance: 'USDM'
                Document: 'USDM v2.6'
              - Cited Guidance: 'SDTMIG'
                Document: 'SDTMIG v3.4'
                Section: '7.2.1'
            Origin: USDM Conformance Rules
            Release Notes: ''
            Rule Identifier:
              Id: 'DDF00029'
              Version: '1'
            Validator Rule Message: ''
            Version: '1.0'
        Version: '3.0'
Check:
  all:
    - name: 'rel_type'
      operator: equal_to
      value: 'definition'
    - any:
        - all:
            # An id value is specified for nextId
            - name: nextId
              operator: non_empty
            # And the specified nextId value is not a valid id for the StudyDesign ...
            - name: nextId
              operator: is_not_contained_by
              value: $encounter_ids_for_study_design
        # Or ...
        - all:
            # An id value is specified for previousId 
            - name: previousId
              operator: non_empty
            # And the specified previousId value is not a valid id for the StudyDesign ...
            - name: previousId
              operator: is_not_contained_by
              value: $encounter_ids_for_study_design
Core:
  Id: CORE-000421
  Status: Draft
  Version: '1'
Description: 'The encounters of a StudyDesign are ordered correctly according to
  the specifed nextId and previousId values.'
Executability: Fully Executable
Operations:
  - group:
      - parent_id
    id: $encounter_ids_for_study_design
    name: id
    operator: distinct
Outcome:
  Message: 'The encounters of a StudyDesign are not ordered correctly according to
    the specifed nextId and previousId values: the id value specified for nextId
    or previousId is not one of the encounter ids for the StudyDesign.'
  Output Variables:
    - parent_entity
    - parent_id
    - id
    - nextId
    - previousId
    - $encounter_ids_for_study_design
Rule Type: Record Data
Scope:
  Entities:
    Include:
      - Encounter
Sensitivity: Record
```
