### ISSUE TITLE
Create rule DDF00027: For classes with next and previous relationships, the next and previous relationships must establish an ordered list of instances of the class (unique nextId and previousId values).

### ISSUE THREAD

**Issue by ASL-rmarshall** [cdisc-org/ddf-core-poc#136]
Create generic rule to check for unique values in nextId and previousId as defined for #89

**Comment by ASL-rmarshall** [comment]
@DianeWold This one is also ready for review. This rule checks for `id` values used more than once in `nextId` or `previousId` (within StudyDesign). It's a generic check that's specified (via Scope) to run for the `Activity`, `EligibilityCriteria`, `Encounter` and `StudyEpoch` classes.

**Comment by DianeWold** [comment]
Ran negative data.  I found 20 errors, but I could find only 11:
For StudyEpoch, 2 errors for each of the two study designs (duplicate nextIds, duplicate previousIds)
For Encounters, 1 error for first study design (dup nextIds) 2 errors for second study design (dups for both nextIds and priorIds)
For Activities, 2 errors (dups for both nextIds and priorIds)
For Eligibiliity criteria, 2 error for first category (dups for both nextIds and priorIds), 
Positive data returned 4 positives. I assume that is one for each of the datasets.

**Comment by ASL-rmarshall** [comment]
@DianeWold I don't think your results quite tally. Each dataset record with a problem is only reported once, even if it has more than one problem.  The 20 reported issues break down like this:
- `StudyEpoch`: total of **7** records with errors:
    - 2 records for the first study design with non-unique `nextId` only (rows 1 and 4)
    - 2 records for the first study design with non-unique `nextId` **and** `previousId` (rows 2 and 3)
    - 1 record for the second study design with non-unique `nextId` only (row 7)
    - 1 record for the second study design with non-unique `nextId` **and** `previousId` (row 8)
    - 1 record for the second study design with non-unique `previousId` only (row 9)
- `Encounter`: total of **6** records with errors:
    - 3 records for the first study design with non-unique `nextId` only (rows 1, 2 and 3)
    - 1 record for the second study design with non-unique `nextId` only (row 5)
    - 1 record for the second study design with non-unique `nextId` **and** `previousId` (row 6)
    - 1 record for the second study design with non-unique `previousId` only (row 7)
- `Activity`: total of **4** records with errors:
    - 2 records with non-unique `nextId` only (rows 1 and 5)
    - 2 records with non-unique `previousId` only (rows 2 and 6)
- `EligibilityCriteria`: total of **3** records with errors:
    - 1 record with non-unique `nextId` only (row 1)
    - 1 record with non-unique `nextId` **and** `previousId` (row 2)
    - 1 record with non-unique `previousId` only (row 3)

7 + 6 + 4 + 3 = 20

**Comment by DianeWold** [comment]
For StudyEpoch, I counted row 8 twice, when it should only be counted once, though it has two problems.
Similar miscount for Encounters.
Count for Activities okay.
For EligibilityCriteria, I counted errors only within a category, but I see now that the check is within a StudyDesign.  That makes sense -- one wouldn't want a criterion twice, even in different categories.
Thanks, @ASL-rmarshall , for the detailed help.
I now understand the results of both the negative and positive testing, and am moving this issue to Done.

**Comment by ASL-rmarshall** [comment]
This rule to only report where `rel_type = "definition"`. Associated test data have been updated and unit tests have been rerun successfully.

**Comment by ASL-rmarshall** [comment]
Saving a copy of the POC rule definition before overwriting for DDF 4:
```yaml
Authorities:
  - Organization: 'CDISC'
    Standards:
      - Name: USDM
        References:
          - Citations:
              - Cited Guidance: 'USDM'
                Document: 'USDM v2.6'
              - Cited Guidance: 'SDTMIG'
                Document: 'SDTMIG v3.4'
                Section: '7.2.1'
            Origin: USDM Conformance Rules
            Release Notes: ''
            Rule Identifier:
              Id: 'DDF00027'
              Version: '1'
            Validator Rule Message: ''
            Version: '1.0'
        Version: '3.0'
Check:
  all:
    - name: rel_type
      operator: equal_to
      value: 'definition'
    - any:
        - all:
            # An id value is specified for nextId and ...
            - name: nextId
              operator: non_empty
            # And the same id value is used more than once for nextId within the StudyDesign.
            - name: nextId
              operator: is_not_unique_set
              value:
                - parent_id
        # Or ...
        - all:
            # An id value is specified for previousId and 
            - name: previousId
              operator: non_empty
            # And the same id value is used more than once for previousId within the StudyDesign.
            - name: previousId
              operator: is_not_unique_set
              value:
                - parent_id
Core:
  Id: CORE-000419
  Status: Draft
  Version: '1'
Description: 'For classes with next and previous relationships, the next and
  previous relationships must establish an ordered list of instances of the
  class. Each nextId and previousId value must only be used once within the
  StudyDesign.'
Executability: Fully Executable
Outcome:
  Message: 'The instances of the class are not ordered correctly according to the
    specifed nextId and previousId values: the same id value has been used more
    than once as nextId or previousId within the StudyDesign.'
  Output Variables:
    - parent_entity
    - parent_id
    - id
    - nextId
    - previousId
Rule Type: Record Data
Scope:
  Entities:
    Include:
      - Activity
      - Encounter
      - EligibilityCriteria
      - StudyEpoch
Sensitivity: Record
```
