### ISSUE TITLE
Create rule: A StudyAmendmentReason is linked to a StudyAmendment either as a primaryReason or as a secondaryReason, but not both.

### ISSUE THREAD

**Issue by ASL-rmarshall** [cdisc-org/ddf-core-poc#140]
Create rule defined for #114

**Comment by ASL-rmarshall** [comment]
@DianeWold This one is also ready for review.  I created test data as follows:
- **Negative**: a total of 10 records, only 8 of which are expected to be reported as errors. There are 4 study amendments, each with a different combination of reasons:
    - StudyAmendment_1: 2 records for a primary reason and one secondary reason, both of which have the same `code.code` value (even though the decodes are different). Both records should be reported as errors.
    - StudyAmendment_2: 3 records for a primary reason and two secondary reasons. The primary reason is "Other" and the secondary reasons have the same `code.code` value (even though the decodes are different). Only the secondary reasons should be reported as errors.
    - StudyAmendment_3: 2 records for a primary reason and one secondary reason, both of which have the same `code.code` value the the `otherReason` values are different. Both records should be reported as errors.
    - StudyAmendment_4: 3 records for a primary reason and two secondary reasons. The primary reason is "IRB/IEC Feedback" and the secondary reasons have the same `code.code` value for "Other", but with different `otherReason` values. Only the secondary reasons should be reported as errors.
 - **Positive**: a total of 5 records, none of which should be reported as an error because the reason codes within each of the two study amendments are unique. (Note that the same code used with different decodes for two study amendments - C99904x2 - is correctly not reported as an error by this rule - but this might suggest the need for another check for a one-to-one relationship between code and decode, probably within the same code system version used across codes in all classes within a study version).

**Comment by DianeWold** [comment]
Negative and positive test data ran as expected.
However, rule may need to be modified to allow multiple instances of the code for "other" if values of otherReason are different.

**Comment by DianeWold** [comment]
Agreed that multiple instances of the code "other" should trigger the rule, as in this case otherReason would have to be checked by hand. Comparing otherReason values electronically could easily miss slight representations of the same reason.

**Comment by BSnoeijerCD** [comment]
@DianeWold and @ASL-rmarshall 
I would say that reasons can be the same across different amendments. So the check should be within an amendment. Not within a study definition. I cannot see whether this is the case based on the Core ruled definition.
Not sure whether multiple instances of Other should trigger the rule. Although I agree with your point Diane, I believe the check description text should then be different - indicating that it could be right but should be checked. While twice filling the same reason is really an error.

**Comment by ASL-rmarshall** [comment]
Saving a copy of the POC rule definition before deleting for DDF 4:
```yaml
Authorities:
  - Organization: 'CDISC'
    Standards:
      - Name: USDM
        References:
          - Citations:
              - Cited Guidance: 'USDM'
                Document: 'USDM v2.6'
            Origin: USDM Conformance Rules
            Release Notes: ''
            Rule Identifier:
              Id: 'DDF00033'
              Version: '1'
            Version: '1.0'
        Version: '3.0'
Check:
  all:
    - name: code.code
      operator: is_not_unique_set
      value:
        - parent_id
Core:
  Id: CORE-000425
  Status: Draft
  Version: '1'
Description: 'For a Study Amendment, the set of codes for StudyAmendmentReason
  must not include duplicates.'
Executability: Fully Executable
Outcome:
  Message: 'The StudyAmendmentReason codes for a StudyAmendment includes duplicates'
  Output Variables:
    - parent_entity
    - parent_id
    - parent_rel
    - id
    - code.code
    - code.decode
    - otherReason
Rule Type: Record Data
Scope:
  Entities:
    Include:
      - StudyAmendmentReason
Sensitivity: Record
```
