### ISSUE TITLE
Create rule DDF00031: If Timing is not of type "fixed reference" then the relationships relativeFromScheduledInstance and relativeToScheduledInstance must link to different ScheduledInstances

### ISSUE THREAD

**Issue by ASL-rmarshall** [cdisc-org/ddf-core-poc#141]
Create rule defined for #131

**Comment by ASL-rmarshall** [comment]
Updated DDF99988 to DDF00031

**Comment by DianeWold** [comment]
Both negative and positive test data ran as expected.
One of the records in the test data isn't an anchor and has a nulll relativeTo relationship, so it has a problem, but not one that violates this rule.

**Comment by ASL-rmarshall** [comment]
This rule to only report where `rel_type = "definition"`. Associated test data have been updated and unit tests have been rerun successfully.

**Comment by ASL-rmarshall** [comment]
Saving a copy of the POC rule definition before overwriting for DDF 4:
```yaml
Authorities:
  - Organization: 'CDISC'
    Standards:
      - Name: USDM
        References:
          - Citations:
              - Cited Guidance: 'USDM'
                Document: 'USDM v2.6'
            Origin: USDM Conformance Rules
            Release Notes: ''
            Rule Identifier:
              Id: 'DDF00031'
              Version: '1'
            Validator Rule Message: ''
            Version: '1.0'
        Version: '3.0'
Check:
  all:
    - name: rel_type
      operator: equal_to
      value: 'definition'
    - not:
        any:
          - name: type.code
            operator: equal_to
            value: C201358
          - name: type.decode
            operator: equal_to_case_insensitive
            value: Fixed Reference
    - name: relativeFromScheduledInstanceId
      operator: equal_to
      value: relativeToScheduledInstanceId
Core:
  Id: CORE-000423
  Status: Draft
  Version: '1'
Description: 'If Timing is not of type "fixed reference" then the relationships
  relativeFromScheduledInstance and relativeToScheduledInstance must link to
  different ScheduledInstances'
Executability: Fully Executable
Outcome:
  Message: 'The Timing is not of type "fixed reference" but the values for
    relativeFromScheduledInstanceId and relativeToScheduledInstanceId are the
    same.'
  Output Variables:
    - parent_entity
    - parent_id
    - parent_rel
    - id
    - type.code
    - type.decode
    - relativeFromScheduledInstanceId
    - relativeToScheduledInstanceId
Rule Type: Record Data
Scope:
  Entities:
    Include:
      - Timing
Sensitivity: Record
```
