### ISSUE TITLE
Create rule DDF00035: Within a StudyVersion, a codeSystem, and a codeSystemVersion, code and decode must be one-to-one.

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/ddf-core-poc#152]
Create rule defined for #142

**Comment by BSnoeijerCD** [comment]
I used the is_not_unique_relationship function to test that only 1 version of a codeSystem is used and the code-decode combinations are unique. However the last one I would like to check within a codeSystem. I cannot add that within information to the is_not_unique_relationship function. The is_not_unique_set is also not working because if you repeatedly use the same combination of codeSystem and codeSystemVersion or code and decode then it will give output. I also tried distinct but that gave a lot of program errors.
So the is_not_unique_relationship is the best option with the caveat that if multiple coding systems use the same code it will trigger output. I have added this to the positive test results.

Ticket #103 covers this issue. So the finalization of the rule is blocked by this ticket.

**Comment by DianeWold** [comment]
Test data ran as expected.  Negative data gave 8 errors.  Positive data gave no errors.

**Comment by ASL-rmarshall** [comment]
Saving copy of POC rule definition before overwriting for DDF4:
```yaml
Authorities:
  - Organization: 'CDISC'
    Standards:
      - Name: USDM
        References:
          - Citations:
              - Cited Guidance: 'USDM'
                Document: 'USDM v2.6'
            Origin: USDM Conformance Rules
            Release Notes: ''
            Rule Identifier:
              Id: 'DDF00035'
              Version: '1'
            Validator Rule Message: ''
            Version: '1.0'
        Version: '3.0'
Check:
  any:
    - name: codeSystem
      operator: is_not_unique_relationship
      value: codeSystemVersion
    - name: decode
      operator: is_not_unique_relationship
      value: code
Core:
  Id: CORE-000427
  Status: Draft
  Version: '1'
Description: 'Within a submitted StudyVersion, a codeSystem and a
  codeSystemVersion, and code and decode must be one-to-one.'
Executability: Fully Executable
Outcome:
  Message: 'Within a submitted StudyVersion, multiple codeSystemVersions are used
    for the same codeSystem, and/or multiple decodes are used for a the same
    code.'
  Output Variables:
    - parent_entity
    - parent_id
    - parent_rel
    - id
    - codeSystem
    - codeSystemVersion
    - code
    - decode
Rule Type: Record Data
Scope:
  Entities:
    Include:
      - Code
Sensitivity: Record
```
