### ISSUE TITLE
Create rule DDF00036: For a Timing from an anchor (with type "fixed reference), relativeToFrom is "start to start"

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/ddf-core-poc#155]
Create rule defined for #119

**Comment by BSnoeijerCD** [comment]
Created rule DDF00036. The check is case insensitive. If type code or decode matches Fixed Reference then it will check whether both code and decode for relativeFromTo matches Start to Start
test data negative:
5 varying cases with either code or decode type matching Fixed Reference and either code or decode relativeFromTo not matching Start to start.
Test data positive:
3 varying cases with either code or decode type matching Fixed reference and code and decode for relativeFromTo matching Start to Start
1 case where code and decode type are not matching Fixed reference.

**Comment by ASL-rmarshall** [comment]
@BSnoeijerCD Rule reviewed and negative/positive tests gave expected results.  Minor question: would it be better for the `Outcome`  `Message` to contains details what is being checked? E.g.

`An anchor (type.code is C201358 or type.decode is "fixed reference", case insensitive) has a relativeToFrom value that is not "start to start" (relativeToFrom.code is C201355 and relativeToFrom.decode is "start to start", case insensitive).`

**Comment by ASL-rmarshall** [comment]
Re-review complete.  Looks good.

**Comment by ASL-rmarshall** [comment]
Saving POC rule definition before overwriting for DDF 4:
``` yaml
Authorities:
  - Organization: 'CDISC'
    Standards:
      - Name: USDM
        References:
          - Citations:
              - Cited Guidance: 'USDM'
                Document: 'USDM v2.6'
            Origin: USDM Conformance Rules
            Release Notes: ''
            Rule Identifier:
              Id: 'DDF00036'
              Version: '1'
            Validator Rule Message: ''
            Version: '1.0'
        Version: '3.0'
Check:
  all:
    - any:
        - name: type.code
          operator: equal_to_case_insensitive
          value: C201358
        - name: type.decode
          operator: equal_to_case_insensitive
          value: Fixed Reference
    - not:
        all:
          - name: relativeToFrom.code
            operator: equal_to_case_insensitive
            value: C201355
          - name: relativeToFrom.decode
            operator: equal_to_case_insensitive
            value: Start to Start
Core:
  Id: CORE-000428
  Status: Draft
  Version: '1'
Description: 'For a Timing from an anchor (with type "fixed reference"),
  relativeToFrom is "start to start"'
Executability: Fully Executable
Outcome:
  Message: 'An anchor (type.code is C201358 or type.decode is "fixed reference",
    case insensitive) has a relativeToFrom value that is not "start to start"
    (relativeToFrom.code is C201355 and relativeToFrom.decode is "start to
    start", case insensitive).'
  Output Variables:
    - parent_entity
    - parent_id
    - parent_rel
    - type.code
    - type.decode
    - relativeToFrom.code
    - relativeToFrom.decode
Rule Type: Record Data
Scope:
  Entities:
    Include:
      - Timing
Sensitivity: Record
```
