### ISSUE TITLE
Create rule DDF00038: The parameterMap attribute of SyntaxTemplateDictionary must be in the correct format.

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/ddf-core-poc#160]
Create rule defined for #149

**Comment by BSnoeijerCD** [comment]
The rule is created with regular expressions. For the ID value I have now allowed any non-whitespace character with no restrictions to length.
The test positive test data includes ids with special characters. 
The negative test data includes different cases of missingness:
   - not aligning to format at all
   - no klass defined
   - no attribute defined
   - " characters not masked by /
   -  no " and / at all

**Comment by DianeWold** [comment]
The test data ran as expected, but I am having trouble matching up the parameterMap values to the examples given in the USDM IG https://wiki.cdisc.org/display/USDMIGv3/Syntax+Templates

**Comment by BSnoeijerCD** [comment]
@DianeWold : please check against the power point I send you (second slide). I will update the IG this week accordingly.

**Comment by DianeWold** [comment]
From the power point, slide 3, it appears that the text of a reference

- starts with "<usdm:tag
- ends with ></usdtm:ref>"
- includes a piece that specifies the class, i.e., klass=\"class name\"
- includes a piece that specifies the class id, i.e., id=\"id value\"
- includes a piece that specifies the class attribute, i.e., attribute=\"attribute name\"

The USDM IG appears to allow an alternative where a reference can be to a fixed value.  Has that been eliminated? Or does the rule need to allow for that alternative?

**Comment by ASL-rmarshall** [comment]
@BSnoeijerCD Is this review on hold until we have determined whether fixed values need to be accommodated?

**Comment by BSnoeijerCD** [comment]
@ASL-rmarshall : I have updated the IG according to the new presentation on Friday. Based on that the code needs to be updated. Both to include fixed values and to include the whole string.

**Comment by BSnoeijerCD** [comment]
The rule worked but was not completely accurate. For v3.0 it should be updated and/or XML checked should be used. To be discussed with team.

**Comment by ASL-rmarshall** [comment]
Saving POC rule definition before overwriting for DDF4:
```yaml
Authorities:
  - Organization: 'CDISC'
    Standards:
      - Name: USDM
        References:
          - Citations:
              - Cited Guidance: 'USDM'
                Document: 'USDM v2.6'
            Origin: USDM Conformance Rules
            Release Notes: ''
            Rule Identifier:
              Id: 'DDF00038'
              Version: '1'
            Validator Rule Message: ''
            Version: '1.0'
        Version: '3.0'
Check:
  all:
    - any:
        - name: parameterMap
          operator: matches_regex
          value: <usdm:ref.*
        - name: parameterMap
          operator: matches_regex
          value: .*ref>
    - all:
        - name: parameterMap
          operator: not_matches_regex
          value: <usdm:ref klass=\\"[a-zA-Z]+\\" id=\\"\S+\\"
            attribute=\\"[a-zA-Z]+\\"></usdm:ref>
Core:
  Status: Draft
  Version: '1'
Description: 'The parameterMap attribute of SyntaxTemplateDictionary must be in
  the correct format.'
Executability: Fully Executable
Outcome:
  Message: 'The paramterMap attribute of SyntaxTemplateDictionary is not in the
    correct format: "<usdm:ref klass=\"...\" id=\"...\"
    attribute=\"....\"></usdm:ref>".'
  Output Variables:
    - id
    - name
    - parameterMap
Rule Type: Record Data
Scope:
  Entities:
    Include:
      - SyntaxTemplateDictionary
Sensitivity: Record
```
