### ISSUE TITLE
Define rule DDF00018: The study protocol version should match the ScheduledTimeline version (aka the schedule of activities).

### ISSUE THREAD

**Issue by nickdedonder** [cdisc-org/ddf-core-poc#20]
CHK0093: Protocol vs Soa version

**Comment by DianeWold** [comment]
The Description currently says "The study protocol version should match the ScheduledTimeline
  version (aka the schedule of activities)." However, the ScheduleTimeline doesn't have an attribute of version or a relationship that connects to a version.  There is a connection through Study Design and StudyVersion to StudyProtocolDocumentVersion, but I think that's just a relationship, not something that assigns a version to a ScheduleTimeline.

**Comment by rbakercdisc1** [comment]
@nickdedonder 
This one does not match USDM. However, in the FHIR Schedule of Activities discussions we have talked about the different parts of the protocol having versions too (they would be versioned at the protocol level but if that particular part was not updated, it might be good to know. The result of the discussion is that the team decided that each piece would inherit the version and the change update would identify where the change occurred.  

Should I reuse this one?

Thank you.

**Comment by drewcdisc** [comment]
It has been reviewed by everyone and determined to be non-executable. The non-executable attribute has been added. This can be moved to done.

**Comment by ASL-rmarshall** [comment]
Rule deleted in DDF Phase 4. Saving a copy of the definition:
```yaml
Authorities:
  - Organization: CDISC
    Standards:
      - Name: USDM
        References:
          - Citations:
              - Cited Guidance: 'USDM'
                Document: 'USDM v2.5'
            Origin: USDM Conformance Rules

            Rule Identifier:
              Id: 'DDF00018'
              Version: '1'
            Validator Rule Message: 'Study Protocol Document Version must match Schedule
              Timeline version'
            Version: '1.0'
        Version: '3.0'
      #StudyProtocolDocumentVersion has protocolVersion attribute which must match the ScheduledInstance scheduleInstanceTimeline version.
      #should there be a version on all classes for version control?

Check:
  any:
    - name: StudyProtocolDocumentVersion
      operator: equal_to
      value: ScheduleTimelineVersion

Core:
  Id: 'CORE-000412'
  Status: Draft
  Version: '1'
Description: The study protocol version should match the ScheduledTimeline
  version (aka the schedule of activities).
Executability: Not Executable
Outcome:
  Message: The study protocol version is misaligned with the schedule of activities.
  Output Variables:
    - StudyProtocolDocumentVersion ScheduleTimeline protocolVersion

Rule Type: Variable Metadata Check

Scope:
  Entities:
    Include:
      - ALL

Sensitivity: Record
```
