### ISSUE TITLE
Create rule DDF00001

### ISSUE THREAD

**Issue by nickdedonder** [cdisc-org/ddf-core-poc#23]

**Comment by ASL-rmarshall** [comment]
This rule has been created for the defined scope of StudyElement, but with the added restriction that name/description should have a 1-to-1 relationship only if both are populated (`description` is optional).

However, this currently does not restrict checking to within study version/design  (see [comment](https://github.com/cdisc-org/ddf-core-poc/issues/3#issuecomment-1804451119) in #3 ).

@gerrycampion Do you think it would be better to have some sort of configuration that can be used to restrict checking to:
- The most recent study version, if more than one is included in a JSON file being checked?
- A particular study design within a study?

**Comment by rbakercdisc1** [comment]
This looks fine and runs as expected.

**Comment by ASL-rmarshall** [comment]
This rule to only report where `rel_type = "definition"`. Associated test data have been updated and unit tests have been rerun successfully.

**Comment by ASL-rmarshall** [comment]
Rule deleted in DDF Phase 4.  Saving a copy of definition:
```yaml
Authorities:
  - Organization: CDISC
    Standards:
      - Name: USDM
        References:
          - Citations:
              - Cited Guidance: 'USDM'
                Document: 'USDM v3.0'
            Origin: USDM Conformance Rules
            Rule Identifier:
              Id: DDF00001
              Version: '1'
            Version: '1.0'
        Version: '3.0'
Check:
  all:
    - name: 'name'
      operator: non_empty
    - name: description
      operator: non_empty
    - name: 'name'
      operator: is_not_unique_relationship
      value: description
    - name: 'rel_type'
      operator: equal_to
      value: 'definition'
Core:
  Id: 'CORE-000399'
  Status: Draft
  Version: '1'
Description: If both are provided, name should have a one-to-one relationship
  with description within StudyElement
Executability: Fully Executable
Outcome:
  Message: StudyElement name does not have a one-to-one relationship with description
  Output Variables:
    - parent_entity
    - parent_id
    - parent_rel
    - id
    - name
    - description
Rule Type: Record Data
Scope:
  Entities:
    Include:
      - StudyElement
Sensitivity: Record
```
