### ISSUE TITLE
Create rule DDF00005: A StudyVersion must have no more than one sponsor identifier

### ISSUE THREAD

**Issue by nickdedonder** [cdisc-org/ddf-core-poc#27]
Create rule defined for #7

**Comment by ASL-rmarshall** [comment]
@gerrycampion I made an attempt to create DDF00005 and didn't make much progress.  I see that you've marked the PBI as being blocked by #42, but this rule could be defined without using regex (e.g. specifying `studyIdentifierScope.type.decode = "Clinical Study Sponsor`").

I tried to get the "not more than one sponsor identifier" part of this rule to work with `present_on_multiple_rows_within` (using logic based on CG0063):
```
Check:
  all:
    - name: 'studyIdentifierScope.type.decode'
      operator: present_on_multiple_rows_within
      within: parent_id
    - name: 'studyIdentifierScope.type.decode'
      operator: equal_to
      value: 'Clinical Study Sponsor'
```
However, it seems that this operator might not be able to handle non-domain datasets and variables (assuming that's what the yellow squiggle under `parent_id` and the `'DataFrame' object has no attribute 'tolist'` error imply). If that's the case, getting `present_on_multiple_rows_within` and `not_present_on_multiple_rows_within` to work with non-domain datasets might be more important that the regex requirement.

There's also the second part of the check ("must have one sponsor identifier").  It seems that this will need some sort of linking between the `StudyIdentifier` and `StudyVersion` datasets.  Ignoring `Match Datasets` for now (because it seems to only work if the join key variable has the same name in both joined datasets, while we'll usually need to join by `\<this_class\>.parent_id = \<parent_class\>.id`), I wondered if it would be possible to use `Operations` to create a lookup list.  However, it seems that most operations are written to be specific for domains and domain variables.
