### ISSUE TITLE
Create rule DDF00006: Timing windows must be fully defined

### ISSUE THREAD

**Issue by nickdedonder** [cdisc-org/ddf-core-poc#28]
Create rule defined for  #8

**Comment by ASL-rmarshall** [comment]
Logic: if any of `timingWindow`, `timingWindowLower` or `timingWindowUpper` is populated in an instance of the `Timing` entity, then all three must be populated

**Comment by ASL-rmarshall** [comment]
This rule has been updated and retested for 2.6. `timingWindow`, `timingWindowLower` and `timingWindowUpper` were renamed to `window`, `windowLower` and `windowUpper` respectively.

**Comment by rbakercdisc1** [comment]
@ASL-rmarshall 

It works okay and looks okay so I am moving it to done.


There are couple questions related more to my understanding. In column P, "relativeToFrom.decode" it is "Start to Start" and then in column U "type.decode" says After except for row 11. Row 11 says Before and the "relativeToScheduledInstanceId in column V is ScheduledActivityInstance_7 whereas column W is "ScheduledActivityInstance_6". I am looking at the "success' example. Will you explain these two columns?

The letters in the description, are those arbitrarily assigned?

**Comment by ASL-rmarshall** [comment]
This rule to only report where `rel_type = "definition"`. Associated test data have been updated and unit tests have been rerun successfully.

**Comment by ASL-rmarshall** [comment]
Saving POC definition before overwriting for DDF4:

```yaml
Authorities:
  - Organization: CDISC
    Standards:
      - Name: USDM
        References:
          - Citations:
              - Cited Guidance: 'USDM'
                Document: 'USDM v3.0'
            Origin: USDM Conformance Rules
            Rule Identifier:
              Id: 'DDF00006'
              Version: '1'
            Validator Rule Message: 'If any part of a timing window is specified then all
              parts should be specified'
            Version: '1.0'
        Version: '3.0'
Check:
  all:
    - name: rel_type
      operator: equal_to
      value: 'definition'
    - any:
        - name: window
          operator: non_empty
        - name: windowLower
          operator: non_empty
        - name: windowUpper
          operator: non_empty
    - not:
        all:
          - name: window
            operator: non_empty
          - name: windowLower
            operator: non_empty
          - name: windowUpper
            operator: non_empty
Core:
  Id: 'CORE-000402'
  Status: Draft
  Version: '1'
Description: 'Timing windows must be fully defined.'
Executability: Fully Executable
Outcome:
  Message: 'Incomplete timing window definition (missing window, windowLower or
    windowUpper)'
  Output Variables:
    - parent_entity
    - parent_id
    - parent_rel
    - id
    - window
    - windowLower
    - windowUpper
Rule Type: Record Data
Scope:
  Entities:
    Include:
      - Timing
Sensitivity: Record
```
