### ISSUE TITLE
Create rule DDF00007: Timing From/To - For anchor then To does not need to be set or could be set the same as From

### ISSUE THREAD

**Issue by nickdedonder** [cdisc-org/ddf-core-poc#29]
Create rule defined for #9

**Comment by ASL-rmarshall** [comment]
Saving a copy of the POC rule definition before overwriting for DDF 4:
```yaml
#Timing From To   For anchor then To does not need to be set or could be set the same as From
Authorities:
  - Organization: CDISC
    Standards:
      - Name: USDM
        References:
          - Citations:
              - Cited Guidance: 'USDM'
                Document: 'USDM v2.5'
            Origin: USDM Conformance Rules
            Rule Identifier:
              Id: 'DDF00007'
              Version: '1'
            Validator Rule Message: 'Anchor timing relativeToScheduledInstanceId is not
              blank or the same as relativeFromScheduledInstanceId'
            Version: '1.0'
        Version: '3.0'
#For anchor then To does not need to be set or could be set the same as From searches

Check:
  all:
    - name: type.decode
      operator: equal_to
      value: Fixed Reference
    - not:
        any:
          - name: relativeToScheduledInstanceId
            operator: empty
          - name: relativeToScheduledInstanceId
            operator: equal_to
            value: relativeFromScheduledInstanceId

Core:
  Id: 'CORE-000403'
  Status: Draft
  Version: '1'
Description: 'For anchor timings (type.decode = Fixed Reference),
  relativeToScheduledInstanceId must be either blank or the same as
  relativeFromScheduledInstanceId'
Executability: Fully Executable
Outcome:
  Message: 'Anchor timing relativeToScheduledInstanceId is not blank or the same
    as relativeFromScheduledInstanceId'
  Output Variables:
    - parent_entity
    - parent_id
    - parent_rel
    - id
    - type.decode
    - relativeFromScheduledInstanceId
    - relativeToScheduledInstanceId
Rule Type: Record Data
Scope:
  Entities:
    Include:
      - Timing

Sensitivity: Record
```
