### ISSUE TITLE
Create rule DDF00008: For each ScheduleInstance there should be either a defaultConditionId or a scheduleTimelineExitId

### ISSUE THREAD

**Issue by nickdedonder** [cdisc-org/ddf-core-poc#30]
Create rule defined for #10

**Comment by rbakercdisc1** [comment]
This one seems wrong. The output provides success and the test data looks okay. However, the rule doesn't align with the message the way I understand it. 

The intent of the rule: "For each ScheduleInstance there should be either a
  defaultConditionId or a timelineExitId"

The rule:

Check:
  any:
    - all:
        - name: defaultConditionId
          operator: empty
        - name: timelineExitId
          operator: empty
    - all:
        - name: defaultConditionId
          operator: non_empty
        - name: timelineExitId
          operator: non_empty

To me this means that the checks looks to see if the "defaultConditionId" and the "timelineExitId" are empty/blank OR if the  the "defaultConditionId" and the "timelineExitId" are not empty/populated. It seems that it should be one or the other. The test data appears like that so the test must need an additional operator. Perhaps in each one attribute should be "empty" and the should be "non_empty". Then vice versa in the following part of the rule.

I am puzzled as to why it works and does not work.

**Comment by ASL-rmarshall** [comment]
@rbakercdisc1 The rule reports an error in either (`any`) of these situations:
- Both (`all`) `defaultConditionId` and `timelineExitId` are blank (`empty`)
- Both (`all`) `defaultConditionId` and `timelineExitId` are populated (`non_empty`)

The only way for the rule not to report an error is if neither situation occurs - i.e., if one, and only one, of `defaultConditionId` and `timelineExitId` is populated - which is what we want.

**Comment by rbakercdisc1** [comment]
Okay, I see now. Thank you.

**Comment by ASL-rmarshall** [comment]
Moved this back to the Done column because (as of 17-Jan-2024), we've only been closing "not planned" issues.

**Comment by ASL-rmarshall** [comment]
This rule to only report where `rel_type = "definition"`. Associated test data have been updated and unit tests have been rerun successfully.

**Comment by ASL-rmarshall** [comment]
Storing POC definition before overwriting for DDF4:
```yaml
#Only one ScheduledInstance should be set per defaultConditionId or timelineExitId. Generally default is set, but if Exit is set then no default. There should be only one, not both.

Authorities:
  - Organization: CDISC
    Standards:
      - Name: USDM
        References:
          - Citations:
              - Cited Guidance: 'USDM'
                Document: 'USDM v2.5'
            Origin: USDM Conformance Rules

            Rule Identifier:
              Id: 'DDF00008'
              Version: '1'
            Validator Rule Message: 'For ScheduledInstance only one defaultConditionId is
              set or one timelineExitId'
            Version: '1.0'
        Version: '3.0'

Check:
  all:
    - name: rel_type
      operator: equal_to
      value: 'definition'
    - any:
        - all:
            - name: defaultConditionId
              operator: empty
            - name: timelineExitId
              operator: empty
        - all:
            - name: defaultConditionId
              operator: non_empty
            - name: timelineExitId
              operator: non_empty
Core:
  Id: 'CORE-000404'
  Status: Draft
  Version: '1'
Description: 'For each ScheduleInstance there should be either a
  defaultConditionId or a timelineExitId'
Executability: Fully Executable
Outcome:
  Message: 'For ScheduledInstance, there should be only one defaultConditionId OR
    only one timelineExitId, not both.'
  Output Variables:
    - parent_entity
    - parent_id
    - parent_rel
    - id
    - timelineExitId
    - defaultConditionId
Rule Type: Record Data
Scope:
  Entities:
    Include:
      - ScheduledActivityInstance
      - ScheduledDecisionInstance
Sensitivity: Record

```
