### ISSUE TITLE
Create rule DDF00009: A conditional activity or procedure must be fully defined. If either isConditional or isConditionalReason is populated, both must be populated.

### ISSUE THREAD

**Issue by nickdedonder** [cdisc-org/ddf-core-poc#31]
Create rule defined for #11

**Comment by ASL-rmarshall** [comment]
@gerrycampion Please could you take a look at this one.  Although the rule works as expected for both positive and negative tests, the rule relies on a boolean value, which is currently specified as a string in the Check specification and test data.  Will this need a new operator, do you think, or will `equal_to` and `not_equal_to` handle this?  Are there any special requirements for representing boolean values in test data (e.g., should we use the Excel TRUE/FALSE values, or are "true"/"false" strings sufficient)?

**Comment by gerrycampion** [comment]
@ASL-rmarshall I think the excel file can remain as-is, but this will require at least a change in the Rule Editor to understand boolean (and other possible primitive json datatypes) using the type specified in Row 3 of the Column's metadata. The previous standards only ever needed Num and Char datatypes:

https://github.com/cdisc-org/conformance-rules-editor/blob/0b42d8c5cb7a409f44cb615ca84d4e63869a26de/src/utils/ExcelDataset.ts#L90-L97

I'm not sure if this will also need an update in the engine's operators to handle the new types. We shouldn't add new ones, but update the ones we have. I've attached the rule editor ticket to this ticket.

**Comment by ASL-rmarshall** [comment]
@DianeWold Thanks - there was actually a problem with the rule definition.  I have now updated the rule definition to reference "true"/"false" as text values for the rule to work.

The rule logic is defined as "If either `isConditional` is not false (which includes true and missing) or `isConditionalReason` is populated, then both `isConditional` should be true and `isConditionalReason` should be populated".

**Comment by DianeWold** [comment]
@ASL-rmarshall Tested again.  
Negative data produced 6 hits, as I would expect.
Positive data produced 2 hits. I don't know how to read the results to figure out which rows produced the hits.

**Comment by ASL-rmarshall** [comment]
@DianeWold I'm assuming that "positive data produced 2 hits" means that, after loading the "positive" test data, you saw this:
![image](https://github.com/cdisc-org/ddf-core-poc/assets/113628824/0e98d928-9125-4ee9-9b81-8a7091fd5142)

To view the "2" things that are reported as positives, you click on the down-arrow to the right of this message to expand the results section.  This displays two windows containing JSON messages.  The first is "Request" and this can be ignored (I think it just contains the information that was sent to the rules engine for checking). The second window, "Results", shows the following:
![image](https://github.com/cdisc-org/ddf-core-poc/assets/113628824/d710d19f-9a24-419f-9d7f-bab78a25ee4c)

The "2 items" at the top is what's being reported as "2" in the "Positives<sup>2</sup>" message and this is an indication that two datasets/"domains" were checked ("ACTIVITY" and "PROCEDURE", which came from the two sheets in the uploaded test data Excel file), and both returned an "executionStatus" of "success" meaning no rule failures were encountered in either.

**Comment by DianeWold** [comment]
Thanks.  When Amy trained me, we didn't actually get to a positive result, so I didn't know what the little green "Positives" bubble with the 2 meant or how to interpret it.  I'll move the rule to Done.
Diane

**Comment by DianeWold** [comment]
I followed Richard's explanation of how to check the meaning of the "Positives 2" message and confirmed that the test was successful.

**Comment by ASL-rmarshall** [comment]
Rule deleted in DDF Phase 4. Saving a copy of the definition:
```yaml
#For Activity and Procedure, if Conditional is true then Reason must be present. If false then reason should be ignored

Authorities:
  - Organization: CDISC
    Standards:
      - Name: USDM
        References:
          - Citations:
              - Cited Guidance: 'USDM'
                Document: 'USDM v2.6'
            Origin: USDM Conformance Rules

            Rule Identifier:
              Id: 'DDF00009'
              Version: '1'
            Validator Rule Message: 'isConditional must have isConditionalReason'
            Version: '1.0'
        Version: '3.0'
      #Activity and Procedure conditional attributes need reasons

Check:
  all:
    - any:
        - name: isConditional
          operator: not_equal_to
          value: false
        - name: isConditionalReason
          operator: non_empty
    - not:
        all:
          - name: isConditional
            operator: equal_to
            value: true
          - name: isConditionalReason
            operator: non_empty

Core:
  Id: 'CORE-000405'
  Status: Draft
  Version: '1'
Description: A conditional activity or procedure must be fully defined. If
  either isConditional is not "false" or isConditionalReason is populated,
  isConditional must be "true" and isConditionalReason must be populated.
Executability: Fully Executable
Outcome:
  Message: The conditional activity or procedure is not fully defined
    (isConditional is not 'true' or isConditionalReason is missing).
  Output Variables:
    - id
    - name
    - isConditional
    - isConditionalReason

Rule Type: Record Data

Scope:
  Entities:
    Include:
      - Activity
      - Procedure

Sensitivity: Record
```
