### ISSUE TITLE
Create rule DDF00010

### ISSUE THREAD

**Issue by nickdedonder** [cdisc-org/ddf-core-poc#32]

**Comment by ASL-rmarshall** [comment]
This rule, which was originally defined to be specific to the `Procedure` class, has now been incorporated into DDF00009 (see #11), so DDF00010 rule that was drafted in the rule editor will not be finalized.

We will need to decide what to do with the unfinished rule in the rule editor.

**Comment by ASL-rmarshall** [comment]
Saving a copy of the original rule definition before reusing rule ID:
```yaml
#Activity and Procedure conditional attributes need reasons - this one is Procedure

Authorities:
  - Organization: CDISC
    Standards:
      - Name: DDF
        References:
          - Citations:
              - Cited Guidance: 'USDM'
                Document: 'USDM v2.5'

            Criteria:
              Logical Expression:
                Condition: 'Conditional Procedure'
                Rule: 'When Procedure is Conditional it must have a condition reason'
              Plain Language Expression: 'For Procedure, if Conditional is true then Reason
                must be present. If false then reason should be ignored'
              Type: Success
            Origin: DDF Conformance Rules
            Rule Identifier:
              Id: 'DDF00010'
              Version: '1'
            Validator Rule Message: 'procedureIsConditional must have procedureIsConditionalReason'
            Version: '1.0'
        Version: '2.0'

Check:
  all:
    - name: 'Procedure'
      operator: contains
      value: If_conditional_true
Core:
  Id: ''
  Status: Draft
  Version: '1'
Description: 'If Procedure is Conditional then procedureIsConditionalReason must be present'
Executability: Fully Executable
Outcome:
  Message: 'If procedureIsConditional is present, must have
    procedureIsConditionalReason present'
  Output Variables:
    - 'Procedure'
Rule Type: Variable Metadata Check
Scope:
  Attributes:
    Include: -procedureIsConditional -procedureIsConditionalReason
  Classes:
    Include: -Procedure
Sensitivity: Record
```
