### ISSUE TITLE
Define rule DDF99999: Each StudyDesign has at least one EligibilityCriteria

### ISSUE THREAD

**Issue by DianeWold** [cdisc-org/ddf-core-poc#51]
CHK0004: There must be at least one instance of the EligibilityCriteria class related to each instance of the StudyDesign class via the eligibilityCriteria relationship.

**Comment by rbakercdisc1** [comment]
@DianeWold This is ready for review. Thank you.

**Comment by DianeWold** [comment]
I think "EligibilityCriteria" is the class, while "eligibilityCriteria" is he relationship from a StudyDesign to an EligibilityCriteria. I'm not sure an instance of the class EligibilityCriteria can be "non-empty"; I don't think it can can have a value such as "True".  So I don't think this sentence of the Description is right, "Each
  StudyDesign must have EligibilityCriteria=True".

**Comment by rbakercdisc1** [comment]
Removed the part about "True". Updated to the relationship of "eligibilityCritiera".  

As far as the logic, that is the Define part so I am leaving that since that is the next step.  Thanks.

**Comment by DianeWold** [comment]
Rule DDF99999 in the rule editor meets criteria for Done.

**Comment by ASL-rmarshall** [comment]
Saving a copy of the definition before deleting for DDF4:
```yaml
#This is a new rule
Authorities:
  - Organization: 'CDISC'
    Standards:
      - Name: USDM
        References:
          - Citations:
              - Cited Guidance: 'USDM'
                Document: 'USDM v2.6'
              - Cited Guidance: 'ICH M11 Template'
                Document: 'https://www.ich.org/page/multidisciplinary-guidelines'
                Item: '1'
                Section: '5-5.4, pages 29-30, Line 514-559, 2022-09-27 Draft Release'
              - Cited Guidance: 'ICH M11 Technical Specification'
                Document: 'https://www.ich.org/page/multidisciplinary-guidelines'
                Item: '2'
                Section: '5.0-5.4, pages 154-163, tables 296-310,  2022-09-27 Draft Release'
            Origin: USDM Conformance Rules
            Release Notes: ''
            Rule Identifier:
              Id: 'DDF99999'
              Version: '1'
            Version: '1.0'
        Version: '3.0'
Check:
  any:
    - all:
        - name: 'StudyDesign'
          operator: 'non_empty'
        - name: 'EligibilityCriteria'
          operator: 'empty'
Core:
  Status: Draft
  Version: '1'
Description: 'Each StudyDesign must have at least one eligibilityCriteria defined.'
Executability: Fully Executable
Outcome:
  Message: 'StudyDesign is missing eligibilityCriteria'
Rule Type: Record Data
Scope:
  Entities:
    Include:
      - StudyDesign
      - EligibilityCriteria

Sensitivity: Record
```
