### ISSUE TITLE
Create rule DDF00017: The Scheduled Timeline should be sequential following the Schedule of Activities according to the visits in the protocol.

### ISSUE THREAD

**Issue by ASL-rmarshall** [cdisc-org/ddf-core-poc#55]
Create rule defined for #19

**Comment by ASL-rmarshall** [comment]
Defined for non executable rule has been created in the rules editor.

**Comment by ASL-rmarshall** [comment]
Rule deleted in DDF Phase 4. Saving a copy of the definition:
```yaml
Authorities:
  - Organization: CDISC
    Standards:
      - Name: USDM
        References:
          - Citations:
              - Cited Guidance: 'USDM'
                Document: 'USDM v2.5'
              - Cited Guidance: 'The protocol trial schema depicts the flow of individual
                  participants through the progression of trial
                  period(s)/epochs. The Schedule of Activities depicts the
                  procedures, activities, and tests. The protocol defined Visits
                  aka Encounters mus follow the protocol defined sequence and
                  include a list of scheduled activities and procedures for that
                  Visit.'
                Document: 'ICH M11 Template'
                Item: '1'
                Section: '1.3, page 22, 5.0, page 29, 5.6, p.30, 8.3-8.10, pages 38-43,
                  2022-09-27 Draft Release'
              - Cited Guidance: 'ICH M11 Technical Specification'
                Document: 'https://www.ich.org/page/multidisciplinary-guidelines'
                Item: '2'
                Section: '1.3, page 114, table 225, 5.0, page 154, table 296, 5.6, page 169,
                  table 323, 8.7, page 261, table 508,  2022-09-27 Draft
                  Release'
            Origin: USDM Conformance Rules

            Rule Identifier:
              Id: 'DDF00017'
              Version: '1'
            Validator Rule Message: 'The ScheduleTimeline should be sequential'
            Version: '1.0'
        Version: '3.0'
        #Schedule of Activity has Schedule Timeline with ScheduledAcitivtyInstance that has activities at each scheduledActivityInstanceEncounter. This rule validates that the ScheduleTimeline is sequential in the Schedule of Activities with the written text in the protocol.
        #The goal for this is to match the order of the encounter schedule timeline with the activites associated with each activity as a group. It appears problematic.
Check:
  all:
    - name: usdm_ScheduleTimeline
      operator: is_ordered_set # match_group(Encounter[Activities])
      value:
        - Activity
        - Procedure
      within: --SMTHNG #'scheduleActivityInstance, Encounter'

Core:
  Id: 'CORE-000411'
  Status: Draft
  Version: '1'
Description: 'The Scheduled Timeline should be sequential following the Schedule
  of Activities according to the visits in the protocol.'
Executability: Not Executable
Outcome:
  Message: 'Protocol text and Schedule of Activity Visits/Encounters with
    associated Activities and Procedures do not match'
  Output Variables:
    - USDM Encounters and defined Activities
Rule Type: Variable Metadata Check
Scope:
  Entities:
    Include:
      - All

Sensitivity: Record
```
