### ISSUE TITLE
Create rule: The study protocol may have conditional activities, these must have   reasons or conditions for the activity.

### ISSUE THREAD

**Issue by ASL-rmarshall** [cdisc-org/ddf-core-poc#58]
Create rule defined in #22

**Comment by ASL-rmarshall** [comment]
Saving a copy of the original rule definition before reusing rule ID:
```yaml
Authorities:
  - Organization: CDISC
    Standards:
      - Name: DDF
        References:
          - Citations:
              - Cited Guidance: 'USDM'
                Document: 'USDM v2.5'
              - Cited Guidance: 'ICH M11 Template'
                Document: 'https://www.ich.org/page/multidisciplinary-guidelines'
                Item: '1'
                Section: '1.3, page 22, 5.0, page 29, 5.6, p.30, 2022-09-27 Draft Release'
              - Cited Guidance: 'ICH M11 Technical Specification'
                Document: 'https://www.ich.org/page/multidisciplinary-guidelines'
                Item: '2'
                Section: '1.3, page 114, table 225, 5.0, page 154, table 296, 5.6, page 169,
                  table 323, 8.7, page 261, table 508,  2022-09-27 Draft
                  Release'
            Origin: DDF Conformance Rules
            Rule Identifier:
              Id: 'DDF00020'
              Version: '1'
            Validator Rule Message: 'Conditional Activity must have a conditional reason in
              Study Activity'
            Version: '1.0'
        Version: '2'
        #This one is from the terminology. In USDM there are conditional activites noted in the Activity class. When the Study Activity is conditional there should be text indicating the conditions for the activity. Once implemented, there will be conditions noted in the data (adverse event maybe?) that will trigger these conditional activities. For the purpose of conformance checks on conditional activities, there will need to be a reason
        #complements DDF00009

Check:
  any:
    - name: activityisConditional
      operator: exists
    - name: activityisConditionalReason
      operator: not_exists

Core:
  Id: ''
  Status: Draft
  Version: '1'
Description: The study protocol may have conditional activities, these must have
  reasons or conditions for the activity.
Executability: Partially Executable
Outcome:
  Message: The conditional activity must have a reason for the activity.
  Output Variables:
    - Activity

Rule Type: Define Item Group Metadata Check
#change this to against USDM?

Scope:
  Entities:
    Include:
      - ALL

Sensitivity: Record
```
