### ISSUE TITLE
Create rule DDF00011: Among the ScheduledTimelines associated with the StudyDesign, no more than one must have the attribute mainTimeline = true

### ISSUE THREAD

**Issue by ASL-rmarshall** [cdisc-org/ddf-core-poc#65]
Create rule defined for #13

**Comment by ASL-rmarshall** [comment]
Similar requirements as #27

**Comment by rbakercdisc1** [comment]
Would it make sense to update the PBI title?  And, is that allowed?

**Comment by rbakercdisc1** [comment]
Reviewed - 
In the data there are 6 rows of data and the rule editor only recognizes 5. It may be because the mainTimeline has a row that is blank and the rule is looking for mainTimeline. It seems like the "name" would be the place to check which is designated as the Main Timeline. The ScheduleTimeline_5 and ScheduleTimeline_6 are both described as the main timeline even though the name is different (Main Timeline and Timeline). 

The rule logic is defined, the test data is defined for both positive and negative.
The rule can execute completely and is not fully executable. It may be that what is described above demonstrates the rule is not fully executable.

**Comment by ASL-rmarshall** [comment]
@rbakercdisc1 

I have changed the rule to "Fully Executable" and have rerun the tests and regenerated results. Thanks.

I assume you mean the positive test data as the negative test data only contains 3 rows.  The rule editor recognizes all 6 rows in the positive test data - you can see this if you look at the JSON in the "Load Test Datasets" section:
![image](https://github.com/cdisc-org/ddf-core-poc/assets/113628824/36962050-4cf9-41df-ad2c-10bca8f4538d)
The 6 rows from the data are also shown in the Request JSON in the Results section.

If you're referring to *`5 items`* in the JSON in the Results JSON:
![image](https://github.com/cdisc-org/ddf-core-poc/assets/113628824/63c702f3-e3f8-4e69-b02f-735c5b70d170)
this is just a reference to the items shown in the JSON, i.e., 
1. `executionStatus`
2. `domain`
3. `variables`
4. `message`
5. `errors`

**Comment by ASL-rmarshall** [comment]
Rewrote the rule to use `is_not_unique_set` instead of `present_on_multiple_rows_within`.  This works with a single group, so removed the blocker from this PBI.

**Comment by ASL-rmarshall** [comment]
This is ready for re-review.

@DianeWold Please use the test data in the 02 folders

**Comment by DianeWold** [comment]
Tried running the positive data again, and did not encounter the error above. Test data okay.

**Comment by ASL-rmarshall** [comment]
Saving a copy of the POC rule definition before deleting for DDF 4:
```yaml
Authorities:
  - Organization: CDISC
    Standards:
      - Name: USDM
        References:
          - Citations:
              - Cited Guidance: 'USDM'
                Document: 'USDM v2.5'
            Origin: USDM Conformance Rules

            Rule Identifier:
              Id: 'DDF00011'
              Version: '1'
            Validator Rule Message: 'ScheduleTimeline must have only one instance of mainTimeline'
            Version: '1.0'
        Version: '3.0'
      #ScheduleTimeline has only one mainTimeline. This is companion to DDF00012.

Check:
  all:
    - name: mainTimeline
      operator: equal_to
      value: true
    - name: mainTimeline
      operator: is_not_unique_set
      value:
        - parent_id

Core:
  Id: 'CORE-000406'
  Status: Draft
  Version: '1'
Description: 'Among the ScheduleTimelines associated with the StudyDesign, no
  more than one must have the attribute mainTimeline = true'
Executability: Fully Executable
Outcome:
  Message: 'StudyDesign must have only one timeline with mainTimeline = true'
  Output Variables:
    - parent_entity
    - parent_rel
    - parent_id
    - id
    - name
    - mainTimeline
Rule Type: Record Data
Scope:
  Entities:
    Include:
      - ScheduleTimeline

Sensitivity: Record
```
