### ISSUE TITLE
Create rule DDF00012: One of the ScheduleTimelines associated with a StudyDesign must have the attribute mainTimeline = true

### ISSUE THREAD

**Issue by ASL-rmarshall** [cdisc-org/ddf-core-poc#66]
Create rule defined for #14

**Comment by DianeWold** [comment]
Does it matter that the test data would fail checks for different ScheduleTimelines having distinct values of name, description, and label?  How realistic does test data need to be?

**Comment by DianeWold** [comment]
I'm not sure why the results for the negative data return 3 errors, one per record, rather than 2 errors, one per ScheduleTimeline.  This is probably because I don't understand the code for the check.

**Comment by BSnoeijerCD** [comment]
> Does it matter that the test data would fail checks for different ScheduleTimelines having distinct values of name, description, and label? How realistic does test data need to be?

@DianeWold, I added some variation to the test data and uploaded it again. No difference in results but I agree that it is good to be more realistic.

**Comment by BSnoeijerCD** [comment]
> I'm not sure why the results for the negative data returns 3 errors, one per record, rather than 2 errors, one per ScheduleTimeline. This is probably because I don't understand the code for the check.

@DianeWold: You can either report by dataset or record. By dataset would mean 1 result for the whole test which is not specific enought. By record means that you get a result for each record in the original dataset that does not comply to the rules. Hence, the records of the studydesign with two timelines which are both not a main timeline are both in the output.

**Comment by DianeWold** [comment]
Ran test data. Negative test data returned 3 records, Positive test data found no errors.

**Comment by ASL-rmarshall** [comment]
This rule has been updated to only report where `rel_type = "definition"`. Associated test data have been updated and unit tests have been rerun successfully.

**Comment by ASL-rmarshall** [comment]
Saving a copy of the POC rule definition before overwriting for DDF 4:
```yaml
Authorities:
  - Organization: CDISC
    Standards:
      - Name: 'USDM'
        References:
          - Citations:
              - Cited Guidance: 'USDMIG'
                Document: 'USDM v3.0'
                Item: text
                Section: '4.14 Study Timing'
            Criteria:
              Logical Expression:
                Condition: ''
                Rule: 'mainTimeline=True'
              Plain Language Expression: 'A mainTimeline should be defined for a StudyDesign'
              Type: ''
            Origin: USDM Conformance Rules
            Rule Identifier:
              Id: 'DDF00012'
              Version: '1'
            Validator Rule Message: 'ScheduleTimeline must have only one instance of mainTimeline'
            Version: '1.0'
        Version: '3.0'
      #ScheduleTimeline has only one mainTimeline and it cannot be null. Companion to DDF00011.
Check:
  all:
    - name: rel_type
      operator: equal_to
      value: 'definition'
    - name: $st_parent_id
      operator: does_not_contain
      value: true
      value_is_literal: true

Core:
  Id: 'CORE-000407'
  Status: Draft
  Version: '1'
Description: 'If scheduledTimelines are defined for a study Design then one of
  the ScheduleTimelines associated with a StudyDesign must have the attribute
  mainTimeline = true'
Executability: Fully Executable
Operations:
  - group:
      - parent_id
    id: $st_parent_id
    name: mainTimeline
    operator: distinct
Outcome:
  Message: 'StudyDesign is missing a mainTimeline'
  Output Variables:
    - parent_entity
    - parent_rel
    - parent_id
    - id
    - name
    - mainTimeline
Rule Type: Record Data
Scope:

  Entities:
    Include:
      - ScheduleTimeline

Sensitivity: Record
```
