### ISSUE TITLE
Create rule DDF00013: If BiomedicalConceptPropertyisRequired=true, then BiomedicalConceptPropertyisEnabled=true

### ISSUE THREAD

**Issue by ASL-rmarshall** [cdisc-org/ddf-core-poc#67]
Create rule defined for #15

**Comment by ASL-rmarshall** [comment]
OK, when creating this rule, make sure that it checks for both of these conditions:
- If `BiomedicalConceptProperty.isRequired` is `true` then `BiomedicalConceptProperty.isEnabled` must also be `true`.
- If `BiomedicalConceptProperty.isEnabled` is `false` then `BiomedicalConceptProperty.isRequired` must also be `false`.

**Comment by ASL-rmarshall** [comment]
This rule is blocked because the engine doesn't yet support true/false boolean values.  I have created the rule using 'true' and 'false' as text values.

**Comment by DianeWold** [comment]
Negative test showed two rows with errors, as expected.
Positive test was successful.

**Comment by ASL-rmarshall** [comment]
Remove block as boolean data types are now supported.

**Comment by ASL-rmarshall** [comment]
Saving a copy of the POC rule definition before overwriting for DDF4:
```yaml
Authorities:
  - Organization: CDISC
    Standards:
      - Name: USDM
        References:
          - Citations:
              - Cited Guidance: 'USDM'
                Document: 'USDM v2.5'
            Origin: USDM Conformance Rules

            Rule Identifier:
              Id: 'DDF00013'
              Version: '1'
            Validator Rule Message: 'In BiomedicalConceptProperty, if isRequired=true then
              isEnabled must be true and if isEnable=false then isRequired must
              be false'
            Version: '1.0'
        Version: '3.0'
      #Biomedical concept rule
Check:
  any:
    - all:
        - name: isRequired
          operator: equal_to
          value: true
        - name: isEnabled
          operator: not_equal_to
          value: true
    - all:
        - name: isEnabled
          operator: equal_to
          value: false
        - name: isRequired
          operator: not_equal_to
          value: false

Core:
  Id: 'CORE-000408'
  Status: Draft
  Version: '1'
Description: 'In BiomedicalConceptProperty, if isRequired=true then isEnabled
  must be true and if isEnable=false then isRequired must be false'
Executability: Fully Executable
Outcome:
  Message: 'A required BiomedicalConceptProperty (isRequired=true) is not enabled
    (isEnabled=true), or a disabled BiomedicalConeptProperty (isEnabled=false)
    is required (isRequired=true)'
  Output Variables:
    - parent_entity
    - parent_id
    - id
    - name
    - isRequired
    - isEnabled
Rule Type: Record Data
Scope:
  Entities:
    Include:
      - BiomedicalConceptProperty
Sensitivity: Record
```
