### ISSUE TITLE
Create rule DDF00015: Study must have a study phase from the controlled terminology list.

### ISSUE THREAD

**Issue by ASL-rmarshall** [cdisc-org/ddf-core-poc#69]
Create rule defined for #17

**Comment by ASL-rmarshall** [comment]
Will need to check both `studyPhase.standardCode.decode` and each `studyPhase.aliasCodes.decode`.  Requires joining tables.

**Comment by ASL-rmarshall** [comment]
@DianeWold This one is ready for review.

I have created this simply as a check that the C-code for the study version's study phase standard code is one of the 17 C-codes defined in the USDM v2.6 CT for `studyPhase`. I created test data as follows:
- **Negative**: 2 study versions, both of which are expected to be reported as an error:
    - One has a `studyPhase.standardCode.code` value that's not in the list
    - The other doesn't have any information for `studyPhase`
- **Positive**: 17 study versions, each with a different C-code from the codelist. No errors should be reported.

**Comment by ASL-rmarshall** [comment]
I had a quick check to see if any of the existing rule operators could be used to check against DDF terminology extracted from the Library, but the terminology operators all seem to rely on Define-XML.  Theoretically, we could try and craft a Define-XML that contains a description of the tabular representation of USDM classes, with the corresponding codelist associations, but I'm not sure that this would be worth the effort (as we'd probably run into Define-XML conformance issues).

**Comment by DianeWold** [comment]
Negative test data fired twice -- one study version had a phase code not in CT, and the other had no phase code.
Positive test ran successfully. Codes were in the list of valid codes in the rule.

**Comment by ASL-rmarshall** [comment]
Saving a copy of the POC rule definition before overwriting for DDF4:
```yaml
Authorities:
  - Organization: CDISC
    Standards:
      - Name: USDM
        References:
          - Citations:
              - Cited Guidance: 'USDM'
                Document: 'USDM v2.5'
            Origin: USDM Conformance Rules
            Rule Identifier:
              Id: 'DDF00015'
              Version: '1'
            Validator Rule Message: 'Trial Phase Required'
            Version: '1.0'
        Version: '3.0'
      #Study entity has studyPhase attribute from CDISC SDTM Trial Phase Terminology which equals Codelist C66737 Trial Phase Response
Check:
  all:
    - name: studyPhase.standardCode.code
      operator: is_not_contained_by
      value:
        - C48660
        - C54721
        - C15600
        - C15693
        - C198366
        - C198367
        - C199990
        - C199989
        - C15601
        - C15694
        - C49686
        - C49688
        - C15602
        - C49687
        - C49689
        - C15603
        - C47865
Core:
  Id: 'CORE-000409'
  Status: Draft
  Version: '1'
Description: 'Study version must have a study phase from the controlled terminology list.'
Executability: Fully Executable
Outcome:
  Message: 'The code for the study phase standard code was not found in the Study
    Phase controlled terminology.'
  Output Variables:
    - parent_entity
    - parent_id
    - id
    - studyTitle
    - versionIdentifier
    - studyPhase.standardCode.code
    - studyPhase.standardCode.codeSystem
    - studyPhase.standardCode.codeSystemVersion
    - studyPhase.standardCode.decode
Rule Type: Record Data
Scope:
  Entities:
    Include:
      - StudyVersion
Sensitivity: Record
```
