### ISSUE TITLE
Create rule DDF00016: studyEpochName should have a one-to-one relationship with studyEpochDescription

### ISSUE THREAD

**Issue by ASL-rmarshall** [cdisc-org/ddf-core-poc#70]
Create rule defined for #18

**Comment by ASL-rmarshall** [comment]
Same logic as DDF00001 (#23)

**Comment by ASL-rmarshall** [comment]
Although the logic for this rule is exactly the same as that for DDF00001, I have created this as a separate rule because we haven't yet decided if DDF00001 should be a generic rule (see discussion in #3).

**Comment by DianeWold** [comment]
Negative and positive tests returned message "absent variable skips"  
"errors":[1 item
0:{2 items
"error":"Column not found in data"
"message":"isEnabled, isRequired"

**Comment by DianeWold** [comment]
Apparently ran the test data against the wrong rule.
Reran tests.
Negative data gave 5 negatives, as expected.
Positive data successful.

**Comment by ASL-rmarshall** [comment]
This rule to only report where `rel_type = "definition"`. Associated test data have been updated and unit tests have been rerun successfully.

**Comment by ASL-rmarshall** [comment]
Rule deleted in DDF Phase 4. Saving a copy of definition:
```yaml
Authorities:
  - Organization: CDISC
    Standards:
      - Name: USDM
        References:
          - Citations:
              - Cited Guidance: 'USDM'
                Document: 'USDM v2.5'
            Origin: USDM Conformance Rules
            Rule Identifier:
              Id: DDF00016
              Version: '1'
            Validator Rule Message: 'StudyEpoch name does not have a one-to-one relationship
              with description'
            Version: '1.0'
        Version: '3.0'
Check:
  all:
    - name: 'name'
      operator: non_empty
    - name: description
      operator: non_empty
    - name: 'name'
      operator: is_not_unique_relationship
      value: description
    - name: 'rel_type'
      operator: equal_to
      value: 'definition'
Core:
  Id: ''
  Status: Draft
  Version: '1'
Description: If both are provided, name should have a one-to-one relationship
  with description within StudyEpoch
Executability: Fully Executable
Outcome:
  Message: StudyEpoch name does not have a one-to-one relationship with description
  Output Variables:
    - parent_entity
    - parent_id
    - parent_rel
    - id
    - name
    - description
Rule Type: Record Data
Scope:
  Entities:
    Include:
      - StudyEpoch
Sensitivity: Record
```
