### ISSUE TITLE
Create rule DDF00019: The study protocol should have an image of the Schedule of Activity (ScheduleTimeline).

### ISSUE THREAD

**Issue by ASL-rmarshall** [cdisc-org/ddf-core-poc#72]
Create rule defined for #21

**Comment by ASL-rmarshall** [comment]
Check that the rule exists in the rule editor with Executability = Not Executable, and all other attributes correct.

**Comment by ASL-rmarshall** [comment]
I made minor changes to the rule definition to prevent yellow lines.

**Comment by rbakercdisc1** [comment]
Discussed with Dave IH and Berber at the extended DDF3 meeting. Consider for future.

**Comment by drewcdisc** [comment]
@nickdedonder We moved this to the icebox as we can't work it until we've considered more for alignment between usdm and m11.

**Comment by ASL-rmarshall** [comment]
Copy of definition before removing from rule editor:
``` yaml
#this is specific to the M11 specification about an imageof the schedule of activity. 
#Question - Although the M11 template says the protocol must have a schedule of activities, in the USDM, the ScheduleTimeline is connected to the StudyDesign. The StudyProtocolDocument connects to the ScheduleTimeline through three intermediate classes, StudyProtocolDocumentVersion, StudyVersion, and StudyDesign. I the that a StudyDesign must have a studyScheduleTimelines relationships to at least one ScheduleTimeline, even though the cardinality on that relationship in the UML is 0...*. 
### What should the approach be?  image for one check and entity in another OR entity only? 
#should all aspects of the checks be in relation to the USDM entity and/or attribute?

Authorities:
  - Organization: CDISC
    Standards:
      - Name: DDF
        References:
          - Citations:
              - Cited Guidance: 'USDM'
                Document: 'USDM v2.5'
              - Cited Guidance: 'ICH M11 Template'
                Document: 'https://www.ich.org/page/multidisciplinary-guidelines'
                Item: '1'
                Section: '1.3, page 22, 5.0, page 29, 5.6, p.30, 2022-09-27 Draft Release'
              - Cited Guidance: 'ICH M11 Technical Specification'
                Document: 'https://www.ich.org/page/multidisciplinary-guidelines'
                Item: '2'
                Section: '1.3, page 114, table 225, 5.0, page 154, table 296, 5.6, page 169,
                  table 323, 8.7, page 261, table 508,  2022-09-27 Draft
                  Release'
            Origin: DDF Conformance Rules
            Rule Identifier:
              Id: 'DDF00019'
              Version: '1'
            Validator Rule Message: 'Study Protocol Document must have Schedule of Activity
              Image (ScheduleTimeline may be called Schema)'
            Version: '1.0'
        Version: '2'
        #StudyProtocolDocument must have a schedule of activity image. in USDM the Schedule of Activities is noted as ScheduledTimeline. The name for the check might be the Study. Having difficulty with reading the USMD UML.

Check:
  any:
    - name: ScheduleTimeline
      operator: exists
      value: ScheduleTimeline

Core:
  Id: ''
  Status: Draft
  Version: '1'
Description: The study protocol should have an image of the Schedule of Activity
  (ScheduleTimeline).
Executability: Not Executable
Outcome:
  Message: The study protocol does not have an image for the Schedule of Activity.
  Output Variables:
    - StudyTimeline

Rule Type: Record Data
#should we have call or attribute presence check?

Scope:
  Entities:
    Include:
      - StudyProtocolDocumentVersion
      - ScheduleTimeline
Sensitivity: Record

```
