### ISSUE TITLE
Create rule DDF00023: StudyEpochs are ordered chronologically (StudyEpoch components)

### ISSUE THREAD

**Issue by ASL-rmarshall** [cdisc-org/ddf-core-poc#73]
Create rule defined for #48

**Comment by ASL-rmarshall** [comment]
I think there will be several components to this rule, each of which must be satisfied within a given StudyDesign. Some components will be checked for each StudyDesign and some for each StudyEpoch:
**StudyEpoch checks (DDF00023)**
- Every StudyEpoch must have one or both of `previous` or `next` StudyEpoch specified. This check must be defined explicitly as it cannot be implemented via cardinalities.
- The id value specified in any `previous` or `next` for a StudyEpoch must be a valid `StudyEpoch.id` value **for the StudyDesign**. (This might be a separate, potentially generic, rule).
- Any StudyEpoch may be referenced no more than once as a `previous` StudyEpoch and no more than once as a `next` StudyEpoch.
- ~~A StudyEpoch cannot reference itself as `previous` or `next` StudyEpoch.~~ *(already implemented as DDF00021 - see #116)*

**StudyDesign checks (DDF00024)**
- Within the StudyDesign there must be:
    - Exactly one StudyEpoch that has `next` specified, but no `previous` specified (the first epoch)
    - Exactly one StudyEpoch that has `previous` specified, but no `next` specified (the last epoch)


- The values of `next` and `previous` must be complementary - i.e.:
    - For the StudyEpoch referenced as `next` from "this" StudyEpoch, the value of the `previous` attribute must match the `id` value for "this" StudyEpoch.
    - For the StudyEpoch referenced as `previous` from "this" StudyEpoch, the value of the `next` attribute must match the `id` value for "this" StudyEpoch.

These components should ensure that StudyEpochs are ordered in a single, non-looping, non-branching series, but there is nothing that can be used to check if the order is chronological.

**Comment by ASL-rmarshall** [comment]
@DianeWold I created separate PBIs for the separate rules to check StudyEpoch and StudyDesign components so that the StudyEpoch rule can be reviewed and marked as done (assuming it's acceptable).  Please review DDF00023.  Thanks

**Comment by DianeWold** [comment]
Ran the positive and negative test data.  Negative test data showed 6 errors, as expected, Positive test data passed.

**Comment by ASL-rmarshall** [comment]
The following check component needs to be modified only to apply to study designs that have more than one epoch:
- Every StudyEpoch must have one or both of `previous` or `next` StudyEpoch specified. This check must be defined explicitly as it cannot be implemented via cardinalities.

As this modification involves StudyDesign-level information (i.e., only one epoch in the study design), the check component may need to be moved into a separate rule.

**Comment by ASL-rmarshall** [comment]
Based on the comment above and [this comment](https://github.com/cdisc-org/ddf-core-poc/issues/89#issuecomment-1908737942) in #89, DDF00023 should be changed to check only for invalid `id` values because both `nextId` and `previousId` may be blank in study designs with only one epoch and checking of `id` uniqueness can be a generic rule.

**Comment by ASL-rmarshall** [comment]
@DianeWold This is now ready for re-testing - the rule now only checks for use of `id` values that are not valid for the StudyDesign instance. Please use the test data files from the 02 folder for both negative and positive.  Thanks

**Comment by DianeWold** [comment]
Ran test data files from the 02 folder.
Negative testing spotted the 6 rows with invalid epochs for the study design.
Positive testing passed.

**Comment by ASL-rmarshall** [comment]
This rule has been updated to only report where `rel_type = "definition"`. Associated test data have been updated and unit tests have been rerun successfully.

**Comment by ASL-rmarshall** [comment]
Saving POC rule definition before overwriting for DDF 4:
```yaml
Authorities:
  - Organization: 'CDISC'
    Standards:
      - Name: USDM
        References:
          - Citations:
              - Cited Guidance: 'USDM'
                Document: 'USDM v2.6'
              - Cited Guidance: 'SDTMIG'
                Document: 'SDTMIG v3.4'
                Section: '7.2.1'
            Origin: USDM Conformance Rules
            Release Notes: ''
            Rule Identifier:
              Id: 'DDF00023'
              Version: '1'
            Validator Rule Message: ''
            Version: '1.0'
        Version: '3.0'
Check:
  all:
    - name: rel_type
      operator: equal_to
      value: 'definition'
    - any:
        - all:
            # An id value is specified for nextId 
            - name: nextId
              operator: non_empty
            # And the specified nextId value is not a valid id for the StudyDesign 
            - name: nextId
              operator: is_not_contained_by
              value: $epoch_ids_for_study_design
        # Or ...
        - all:
            # An id value is specified for previousId 
            - name: previousId
              operator: non_empty
            # And the specified previousId value is not a valid id for the StudyDesign 
            - name: previousId
              operator: is_not_contained_by
              value: $epoch_ids_for_study_design
Core:
  Id: "CORE-000416"
  Status: Draft
  Version: '1'
Description: 'The StudyEpochs of a StudyDesign are ordered correctly according
  to the specifed nextId and previousId values.'
Executability: Fully Executable
Operations:
  - group:
      - parent_id
    id: $epoch_ids_for_study_design
    name: id
    operator: distinct
Outcome:
  Message: 'The StudyEpochs of a StudyDesign are not ordered correctly according
    to the specifed nextId and previousId values: the id value specified for
    nextId or previousId is not one of the epoch ids for the StudyDesign.'
  Output Variables:
    - parent_entity
    - parent_id
    - id
    - nextId
    - previousId
    - $epoch_ids_for_study_design
Rule Type: Record Data
Scope:
  Entities:
    Include:
      - StudyEpoch
Sensitivity: Record
```
