### ISSUE TITLE
Create rule DDF00004: If AdministrationDuration has durationWillVary true, then reasonDurationWillVary must be present

### ISSUE THREAD

**Issue by ASL-rmarshall** [cdisc-org/ddf-core-poc#92]
Create rule defined for #85

**Comment by ASL-rmarshall** [comment]
Rule finalised as (repurposed) DDF00004.

**Comment by rbakercdisc1** [comment]
Review complete.  The logic is defined, the positive and negative test data is defined. The rule executes completely for both success and failure.

**Comment by ASL-rmarshall** [comment]
Saving POC rule definition before overwriting for DDF4:
```yaml
#If AdministrationDuration has durationWillVary true, then reasonDurationWillVary must be present

Authorities:
  - Organization: CDISC
    Standards:
      - Name: USDM
        References:
          - Citations:
              - Cited Guidance: 'USDM'
                Document: 'USDM v2.6'
            Origin: USDM Conformance Rules

            Rule Identifier:
              Id: 'DDF00004'
              Version: '1'
            Validator Rule Message: 'If AdministrationDuration has durationWillVary true,
              then reasonDurationWillVary must be present'
            Version: '1.0'
        Version: '3.0'

Check:
  all:
    - any:
        - name: durationWillVary
          operator: not_equal_to
          value: false
        - name: reasonDurationWillVary
          operator: non_empty
    - not:
        all:
          - name: durationWillVary
            operator: equal_to
            value: true
          - name: reasonDurationWillVary
            operator: non_empty

Core:
  Id: 'CORE-000400'
  Status: Draft
  Version: '1'
Description: A variable administration duration must be fully defined. If either
  durationWillVary is not "false" or reasonDurationWillVary is populated,
  durationWillVary must be "true" and reasonDurationWillVary must be populated.
Executability: Fully Executable
Outcome:
  Message: The variable AdministrationDuration is not fully defined
    (durationWillVary is not 'true' or reasonDurationWillVary is missing).
  Output Variables:
    - id
    - description
    - durationWillVary
    - reasonDurationWillVary

Rule Type: Record Data

Scope:
  Entities:
    Include:
      - AdministrationDuration

Sensitivity: Record
```
