### ISSUE TITLE
Create rule DDF00014: If a class has a name and a label, the label and name must be one to one

### ISSUE THREAD

**Issue by ASL-rmarshall** [cdisc-org/ddf-core-poc#93]
Create rule defined for #88

**Comment by ASL-rmarshall** [comment]
Rule deleted as superfluous in DDF Phase 4. Saving a copy of the definition:
```yaml
#If a class/entity has a name and a label, the label and name must be one to one

Authorities:
  - Organization: CDISC
    Standards:
      - Name: USDM
        References:
          - Citations:
              - Cited Guidance: 'USDM'
                Document: 'USDM v2.6'
            Origin: USDM Conformance Rules

            Rule Identifier:
              Id: 'DDF00014'
              Version: '1'
            Validator Rule Message: 'If a class/entity has a name and a label, the label and
              name must be one to one'
            Version: '1.0'
        Version: '3.0'

Check:
  all:
    - name: 'name'
      operator: non_empty
    - name: label
      operator: non_empty
    - name: 'name'
      operator: is_not_unique_relationship
      value: label

Core:
  Id: ''
  Status: Draft
  Version: '1'
Description: If a class/entity has a name and a label, the label and name must
  be one to one.
Executability: Fully Executable
Outcome:
  Message: There is more than one class/entity name for a label, or more than one
    label for a name for a class/entity.
  Output Variables:
    - parent_entity
    - parent_id
    - parent_rel
    - id
    - name
    - label
Rule Type: Record Data

Scope:
  Entities:
    Include:
      - All

Sensitivity: Record
```
