### ISSUE TITLE
Create rule DDF00010: If a class has a name and a description, the name and description must be one to one.

### ISSUE THREAD

**Issue by ASL-rmarshall** [cdisc-org/ddf-core-poc#94]
Create rule defined for #87

**Comment by ASL-rmarshall** [comment]
Rule ID changed from DDF99994 to (repurposed) DDF00010.

**Comment by ASL-rmarshall** [comment]
Rule deleted as superfluous in DDF Phase 4

**Comment by ASL-rmarshall** [comment]
Saving a copy of the POC rule definition before overwriting for DDF 4:
```yaml
#If a class/entity has a name and a description, the name and description must be one to one.

Authorities:
  - Organization: CDISC
    Standards:
      - Name: USDM
        References:
          - Citations:
              - Cited Guidance: 'USDM'
                Document: 'USDM v2.6'
            Origin: USDM Conformance Rules

            Rule Identifier:
              Id: 'DDF00010'
              Version: '1'
            Validator Rule Message: 'If a class/entity has a name and a description, the
              name and description must be one to one.'
            Version: '1.0'
        Version: '3.0'

Check:
  all:
    - name: 'name'
      operator: non_empty
    - name: description
      operator: non_empty
    - name: 'name'
      operator: is_not_unique_relationship
      value: description

Core:
  Id: ''
  Status: Draft
  Version: '1'
Description: If a class has a name and a description, the name and description
  must be one to one.
Executability: Fully Executable
Outcome:
  Message: There is more than one class/entity name for a description, or more
    than one description for a name for a class/entity.
  Output Variables:
    - parent_entity
    - parent_id
    - parent_rel
    - id
    - name
    - description
Rule Type: Record Data

Scope:
  Entities:
    Include:
      - All

Sensitivity: Record
```
